## roles/kerberos-kdc/tasks/main.yml
## Role main file
# vim:ft=ansible:
---
- name: "Assert that we are in a valid environment"
  assert:
    that:
      - "'RedHat' in ansible_os_family"
    msg: "Only RedHat family supported at this time."

- name: Ensure that needed packages are installed
  package:
    name: '{{ item  }}'
    state: present
  with_items:
    - krb5-server
    - krb5-workstation

- name: Ensure that server configuration files are present
  template:
    src: '{{ item }}.j2'
    dest: /var/kerberos/krb5kdc/{{ item }}
  with_items:
    - kadm5.acl
    - kdc.conf

- name: Ensure that client configuration file is present
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: Is there a database already?
  stat:
    path: /var/kerberos/krb5kdc/principal
  register: db_exists

- name: Create the KDC Database
  command: /bin/bash -c "echo -e '{{ krb5_kdc_master_key }}\n{{ krb5_kdc_master_key }}' | kdb5_util create -s -r '{{ krb5_kdc_realm }}'"
  when: db_exists.stat.exists == false

- name: Ensure that Kerberos services are enabled and started
  service:
    name: '{{ item }}'
    state: reloaded
    enabled: yes
  with_items:
    - krb5kdc
    - kadmin

- name: Create and install principals
  block:
    - name: "Create admin principal"
      command: /bin/bash -c "echo -e '{{ krb5_kdc_master_key }}\n{{ krb5_kdc_master_key }}' | kadmin.local -q 'addprinc root/admin'"

    - name: "Create host principal"
      command: /bin/bash -c "echo -e '{{ krb5_kdc_master_key }}\n{{ krb5_kdc_master_key }}' | kadmin.local -q 'addprinc -randkey host/{{ krb5_kdc_server }}'"

    - name: "Copy host principal to keytab"
      command: /bin/bash -c "echo -e '{{ krb5_kdc_master_key }}\n{{ krb5_kdc_master_key }}' | kadmin.local -q 'ktadd host/{{ krb5_kdc_server }}'"
  when: db_exists.stat.exists == false
